### ISSUE TITLE
Error building docker-compose image

### ISSUE THREAD

**Issue by Bastika07** [SirChri/employee-shift-scheduler#12]
> [build-stage 6/6] RUN npm run build:
#0 0.631
#0 0.631 > my-admin@0.1.0 build
#0 0.631 > react-scripts build
#0 0.631
#0 2.421 Creating an optimized production build...
#0 5.790 One of your dependencies, babel-preset-react-app, is importing the
#0 5.790 "@babel/plugin-proposal-private-property-in-object" package without
#0 5.790 declaring it in its dependencies. This is currently working because
#0 5.790 "@babel/plugin-proposal-private-property-in-object" is already in your
#0 5.790 node_modules folder for unrelated reasons, but it may break at any time.
#0 5.790
#0 5.790 babel-preset-react-app is part of the create-react-app project, which
#0 5.790 is not maintianed anymore. It is thus unlikely that this bug will
#0 5.790 ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
#0 5.790 your devDependencies to work around this error. This will make this message
#0 5.790 go away.
#0 5.790
#0 138.1 The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1

**Comment by SirChri** [comment]
Hello,
as the error suggests, you don't have sufficient memory (RAM) to build the client.
Here's a related problem -> https://github.com/facebook/create-react-app/issues/3862

**Comment by Bastika07** [comment]
Ah! Thanks! Now it is working
