### ISSUE TITLE
Docker-composer run 

### ISSUE THREAD

**Issue by BoodziooPL** [SirChri/employee-shift-scheduler#21]
=> ERROR [client build-stage 6/6] RUN npm run build                                                                                                                                                                      138.1s 
------
 > [client build-stage 6/6] RUN npm run build:
1.057
1.057 > my-admin@0.1.0 build
1.057 > react-scripts build
1.057
5.095 Creating an optimized production build...
8.782 One of your dependencies, babel-preset-react-app, is importing the
8.782 "@babel/plugin-proposal-private-property-in-object" package without
8.782 declaring it in its dependencies. This is currently working because
8.782 "@babel/plugin-proposal-private-property-in-object" is already in your
8.782 node_modules folder for unrelated reasons, but it may break at any time.
8.782
8.782 babel-preset-react-app is part of the create-react-app project, which
8.782 is not maintianed anymore. It is thus unlikely that this bug will
8.782 ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
8.782 your devDependencies to work around this error. This will make this message
8.782 go away.
8.782
137.6 Failed to compile.
137.6
137.6 /client/src/i18n/it.tsx
137.6 TypeScript error in /client/src/i18n/it.tsx(5,9):
137.6 Property 'update_application' is missing in type '{ add_filter: string; add: string; back: string; bulk_actions: string; cancel: string; clear_array_input: string; clear_input_value: string; clone: string; confirm: string; create: string; create_item: string; ... 25 more ...; select_columns: string; }' but required in type '{ [key: string]: string | StringMap; add_filter: string; add: string; back: string; bulk_actions: string; cancel: string; clear_array_input: string; clear_input_value: string; ... 30 more ...; update_application: string; }'.  TS2741
137.6
137.6     3 | const customItalianMessages: TranslationMessages = {
137.6     4 |     ra: {
137.6   > 5 |         action: {
137.6       |         ^
137.6     6 |           add_filter: 'Aggiungi un filtro',
137.6     7 |           add: 'Aggiungi',
137.6     8 |           back: 'Indietro',
137.6
137.6
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1

**Comment by xnhbwj** [comment]
Ran into the exact same problem in test……

**Comment by SirChri** [comment]
Hi, I updated the app and the backend has been rewritten in java from scratch. Also I fixed the error you faced. Could you please retry?

Thanks

**Comment by xnhbwj** [comment]
Yes, the deploy goes smooth this time, while function test also went well at the beginning.

However, it seem that the CREATE and DELETE function of EMPLOYEES and CLIENTI is fine, but the EDIT function often ends up in a "Server communication error". By deleting and creating new ones could somehow bypass this problem.

Thank you very much!

**Comment by SirChri** [comment]
@xnhbwj 

> Yes, the deploy goes smooth this time, while function test also went well at the beginning.
> 
> However, it seem that the CREATE and DELETE function of EMPLOYEES and CLIENTI is fine, but the EDIT function often ends up in a "Server communication error". By deleting and creating new ones could somehow bypass this problem.
> 
> Thank you very much!

Thanks for reporting this. I've fixed the issue in the latest release (version 0.9.1). Please feel free to upgrade to the latest version to have this problem resolved.

I'm closing this issue now. If you encounter any further issues, I suggest opening a new ticket.
